<?php

namespace ReclamationBundle\Repository;

/**
 * NotificationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationsRepository extends \Doctrine\ORM\EntityRepository
{
}
