<?php

namespace ReclamationBundle\Repository;

/**
 * reclamationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reclamationsRepository extends \Doctrine\ORM\EntityRepository
{

}
