<?php

namespace ProfileBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllComments($id){
        $query = $this->getEntityManager()
            ->createQuery("SELECT f FROM ProfileBundle:Commentaire f  WHERE f.user='$id'");
        return $query->getResult();

    }

}
