<?php

namespace ProfileBundle\Repository;

/**
 * CompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCompetences($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT a.nomTag FROM ProfileBundle:Competence f LEFT JOIN f.tags a WHERE f.user='$id'");
        return $query->getResult();
    }
    public function getAllCompetences($id){
        $query = $this->getEntityManager()
            ->createQuery("SELECT f FROM ProfileBundle:Competence f  WHERE f.user='$id'");
        return $query->getResult();

    }

}
