<?php

namespace ProfileBundle\Repository;

/**
 * LangueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangueRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLangues($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT f FROM ProfileBundle:Langue f WHERE f.user='$id'");
        return $query->getResult();
    }
}
