profile_homepage:
    path:     /RedirectCreateProfile
    defaults: { _controller: ProfileBundle:Default:redirect }
create_profile_page:
    path:     /createProfile
    defaults: { _controller: ProfileBundle:Default:create }
description_profile_page:
    path:     /DescriptionProfileF/{id}
    defaults: { _controller: ProfileBundle:Default:DescriptionProfile }
visualiser_profile_page:
    path:     /visualiserProfileF
    defaults: { _controller: ProfileBundle:Default:visualiserProfile }
modifier_formation_page:
    path:     /ModifierFormation/{id}
    defaults: { _controller: ProfileBundle:Formation:modifierFormation }
supprimer_formation_page:
    path:     /SupprimerFormation/{id}
    defaults: { _controller: ProfileBundle:Formation:supprimerFormation }
modifier_experiencepro_page:
    path:     /Modifierexperience/{id}
    defaults: { _controller: ProfileBundle:ExperiencePro:modifierExp }
supprimer_experiencepro_page:
    path:     /SupprimerExp/{id}
    defaults: { _controller: ProfileBundle:ExperiencePro:supprimerExp }
modifier_langue_page:
    path:     /Modifierlangue/{id}
    defaults: { _controller: ProfileBundle:Langue:modifierlangue }
supprimer_langue_page:
    path:     /SupprimerLangue/{id}
    defaults: { _controller: ProfileBundle:Langue:supprimerlangue }
supprimer_portfolio_page:
    path:     /Supprimerportfolio/{id}
    defaults: { _controller: ProfileBundle:Portfolio:supprimerportfolio }
lister_freelancers_page:
    path:     /listerFreelancers
    defaults: { _controller: ProfileBundle:Default:listerFreelancers }
lister_notification:
    path:     /listerNotification
    defaults: { _controller: ProfileBundle:Default:displayNotification }
freelancer_disponible:
    path:     /disponible/{id}
    defaults: { _controller: ProfileBundle:Default:disponible }
freelancer_indisponible:
    path:     /indisponible/{id}
    defaults: { _controller: ProfileBundle:Default:indisponible }
employeur_create_profile:
    path:     /CreateProfileEmployeur
    defaults: { _controller: ProfileBundle:Default:createEmployeur }
employeur_view_profile:
    path:     /ViewProfileEmployeur
    defaults: { _controller: ProfileBundle:Default:viewProfileEmployeur }
lister_employeur:
    path:     /listeEmployeur
    defaults: { _controller: ProfileBundle:Default:listEmployeur }
description_profil_employeur:
    path:     /descriptionEmployeur/{id}
    defaults: { _controller: ProfileBundle:Default:descriptionEmployeur }
search_freelancers_by_pays:
    path:     /searchFreelancersByPays
    defaults: { _controller: ProfileBundle:Default:searchFreelancersByPays }
search_freelancers_by_Prix:
    path:     /searchFreelancersByPrix
    defaults: { _controller: ProfileBundle:Default:searchFreelancersByPrix }
search_freelancers_by_disponibilite:
    path:     /searchFreelancersByDisponibilite
    defaults: { _controller: ProfileBundle:Default:searchFreelancersByDisponibilite}
search_freelancers_by_categorie:
    path:     /searchFreelancersByCategorie
    defaults: { _controller: ProfileBundle:Default:searchFreelancersByCategorie}
