<?php

namespace EvenementBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function nbrplace($id)
    {
        $dqlresult=$this->getEntityManager()->createQuery("UPDATE EvenementBundle:Evenement e SET e.nbr_place=e.nbr_place-1 WHERE e.id='$id'");
        return $dqlresult->getResult();
    }
}
