<?php

namespace ArticleBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function mesArticles($currentUserId)
    {
        $dqlresult = $this->getEntityManager()->createQuery("SELECT a FROM ArticleBundle:Article a WHERE a.utilisateur=:idUser ORDER BY a.dateHeure DESC")
            ->setParameter('idUser', $currentUserId);
        return $dqlresult->getResult();
    }

    public function articlesOrdonnes()
    {
        $dqlresult = $this->getEntityManager()->createQuery("SELECT a FROM ArticleBundle:Article a ORDER BY a.dateHeure DESC");
        return $dqlresult->getResult();
    }

    public function rechercheParNom($nomArticle)
    {
        $dqlresult = $this
            ->getEntityManager()
            ->createQuery("SELECT a, u, t FROM ArticleBundle:Article a JOIN a.utilisateur u JOIN a.type t WHERE a.titre LIKE :nomArticle")
            ->setParameter('nomArticle', '%' . $nomArticle . '%');
        return $dqlresult->getArrayResult();
    }
}
