<?php

namespace ProjetBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByIdUser($iduser)
    { $dqlresult=$this->getEntityManager()->createQuery("SELECT V FROM ProjetBundle:Projet V WHERE V.employeur=:iduser")
        ->setParameter('iduser',$iduser);

        return $dqlresult->getResult();
    }



}
