<?php

namespace ProfileBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategories($id,$categorie)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT f FROM ProfileBundle:Categorie f WHERE f.user='$id' And f.nomCategorie='$categorie'");
        return $query->getResult();
    }
}
