<?php

namespace ProfileBundle\Repository;

/**
 * ExperienceProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceProRepository extends \Doctrine\ORM\EntityRepository
{
    public function findExperiences($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT f FROM ProfileBundle:ExperiencePro f WHERE f.user='$id'");
        return $query->getResult();
    }
}
