<?php

namespace ProfileBundle\Repository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFormations($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT f FROM ProfileBundle:Formation f WHERE f.user='$id'");
        return $query->getResult();
    }
}
