<?php

namespace ProfileBundle\Repository;

/**
 * PortFolioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortFolioRepository extends \Doctrine\ORM\EntityRepository
{
    public function findportfolio($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT f FROM ProfileBundle:PortFolio f WHERE f.user='$id'");
        return $query->getResult();
    }
}
