<?php

namespace ProfileBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends \Doctrine\ORM\EntityRepository
{


    public function getRate($idemp, $idfree)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT f FROM ProfileBundle:Rate f WHERE f.idEmployeur=:idEmp AND f.idFrellancer=:idFree")->setParameter('idEmp', $idemp)->setParameter('idFree', $idfree);
        return $query->getResult();
    }


}
