<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function findFreelancersByPays($pays)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT f FROM AppBundle:User f WHERE f.pays='$pays'");
        return $query->getResult();
    }

    public function findFreelancersByTarif($prixmin,$prixmax)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT f FROM AppBundle:User f WHERE f.tarifMoyen>='$prixmin' AND f.tarifMoyen<='$prixmax'")
          ;
        return $query->getResult();
    }
    public function findFreelancersByDidponibilite($dispo)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT f FROM AppBundle:User f WHERE f.disponibilite=true")
        ;
        return $query->getResult();
    }
    public function findAllFreelancers(){

        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT u FROM AppBundle:User u WHERE u.roles LIKE :role'
            )->setParameter('role', '%"ROLE_FREELANCER"%'
            );
        return $query->getResult();
    }

}
