<?php

namespace ForumBundle\Repository;

/**
 * questionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class questionRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindall($contenu)
    {
        $dqlresult=$this->getEntityManager()
            ->createQuery("SELECT m FROM ForumBundle:question m where m.contenu='$contenu'");
        return $dqlresult->getResult();
    }

}
