<?php

namespace ProjetBundle\Repository;

/**
 * CatégorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatégorieRepository extends \Doctrine\ORM\EntityRepository
{
}
