<?php

namespace ProjetBundle\Repository;

/**
 * DemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDemandeByIdUser($iduser)
    { $dqlresult=$this->getEntityManager()->createQuery("SELECT V FROM ProjetBundle:Demande V WHERE V.employeur=:iduser")
        ->setParameter('iduser',$iduser);

        return $dqlresult->getResult();
    }
    public function findDemandeByIdFreelancer($iduser)
    { $dqlresult=$this->getEntityManager()->createQuery("SELECT V FROM ProjetBundle:Demande V WHERE V.freelancer=:iduser")
        ->setParameter('iduser',$iduser);

        return $dqlresult->getResult();
    }

    public function rechercheProjetParCategorie($date)
    { $dqlresult=$this->getEntityManager()->createQuery("SELECT V FROM ProjetBundle:Demande V WHERE V.dateDemande<:date")
        ->setParameter('date',$date);
        return $dqlresult->getResult();
    }

}
