<?php

namespace ProjetBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNotSeen(){
        $dqlresult=$this->getEntityManager()->createQuery("SELECT m FROM ProjetBundle:Notification m WHERE m.seen=0");
        return $dqlresult;

    }
}
