reclamation_homepage:
    path:     /
    defaults: { _controller: ReclamationBundle:Default:index }
reclamation_ajout:
    path:     /reclamation
    defaults: { _controller: ReclamationBundle:reclamations:ajout}
reclamation_affiche:
    path:     /afficher
    defaults: { _controller: ReclamationBundle:reclamations:affiche}
reclamation_supprimer:
    path:     /supprimer/{ref}
    defaults: { _controller: ReclamationBundle:reclamations:supprimer}
categorie_affiche:
    path:     /afficherC
    defaults: { _controller: ReclamationBundle:Categorie:afficheC}
categorie_modifier:
    path:     /afficherC/{id}
    defaults: { _controller: ReclamationBundle:Categorie:modifierC}
categorie_supprimer:
    path:     /supprimerC/{id}
    defaults: { _controller: ReclamationBundle:Categorie:supprimerC}
categorie_ajouter:
    path:     /ajoutCategorie
    defaults: { _controller: ReclamationBundle:Categorie:ajoutC}
reclamation_afficheadmin:
    path:     /affichea
    defaults: { _controller: ReclamationBundle:reclamations:affichea}
supp_user:
    path:     /suppUser/{i}/{id}
    defaults: { _controller: ReclamationBundle:reclamations:suppUser}
envoie_notif:
    path:     /notif
    defaults: { _controller: ReclamationBundle:Default:notification}
admin:
    path:     /admin
    defaults: { _controller: ReclamationBundle:Default:admin }
reclamationR:
    path:     /adminR
    defaults: { _controller: ReclamationBundle:Default:adminR }
mail:
    path:     /mail/{id}
    defaults: { _controller: ReclamationBundle:Default:mail }
reclamationC:
    path:     /adminC
    defaults: { _controller: ReclamationBundle:Categorie:afficheCa }
supprimerR:
    path:     /supprimerC/{id}
    defaults: { _controller: ReclamationBundle:Categorie:supprimerC}
modifierCa:
    path:     /modifierca/{id}
    defaults: { _controller: ReclamationBundle:Categorie:modifierCa}
categorieA:
    path:     /ajoutCa
    defaults: { _controller: ReclamationBundle:Categorie:ajoutCa}
categorieSupp:
    path:     /categorieSupp/{id}
    defaults: { _controller: ReclamationBundle:Categorie:categorieSupp}
index:
    path:     /index
    defaults: { _controller: ReclamationBundle:reclamations:index }
    methods:  GET